[package]
name = "notary"
version = "0.1.0"
description = "Notary: PDA tabanlı belge kanıtı (CONTRACT.md v2)"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "notary"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build"]

[dependencies]
anchor-lang = "0.30.1"
